version: "3"
services:
  redisdb:
    image: redis:latest
    container_name: redisdb
    restart: always
  backend:
    build: .
    container_name: backend
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
      DOMAIN: requestrepo.com
      JWT_SECRET: changethis
      REDIS_HOST: redisdb
    depends_on:
      - redisdb