version: "3"
services:
  redisdb:
    image: redis:latest
    command: redis-server --appendonly yes --maxmemory 16gb --maxmemory-policy allkeys-lru --maxclients 1048576
    container_name: requestrepo_redisdb
    restart: always
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 60s
      timeout: 20s
      retries: 5
      start_period: 10s
  backend:
    build:
      context: .
      args:
        - DOMAIN=${DOMAIN:-requestrepo.com}
    container_name: requestrepo_backend
    restart: always
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env
    environment:
      - REDIS_HOST=requestrepo_redisdb
    depends_on:
      - redisdb
    volumes:
      - backend_cert:/app/cert
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1:80'
      interval: 60s
      timeout: 20s
      retries: 5
      start_period: 10s
  dns:
    build:
      context: ./
      dockerfile: ./dns/Dockerfile
    container_name: requestrepo_dns
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    env_file:
      - .env
    environment:
      - REDIS_HOST=requestrepo_redisdb
    depends_on:
      - redisdb
   healthcheck:
      test: ["CMD", "pgrep", "python3"]
      interval: 60s
      timeout: 20s
      retries: 5
      start_period: 10s
volumes:
  redis_data:
  backend_cert:
