version: "3"
services:
  redisdb:
    image: redis:latest
    container_name: redisdb
    restart: always
    volumes:
      - redis_data:/data
  backend:
    build: .
    container_name: backend
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
      DOMAIN: requestrepo.com
      JWT_SECRET: changethis
      REDIS_HOST: redisdb
      INCLUDE_SERVER_DOMAIN: "true"
    depends_on:
      - redisdb
    volumes:
      - ./backend/pages:/app/pages
  dns:
    build:
      context: ./dns
    container_name: dns
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      DOMAIN: requestrepo.com
      REDIS_HOST: redisdb
      SERVER_IP: 130.61.138.67
    depends_on:
      - redisdb
