version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: requestrepouser
      MONGO_INITDB_ROOT_PASSWORD: changethis
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
  dns:
    build:
      context: ./dns
    container_name: dns
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      MONGODB_DATABASE: requestrepo
      MONGODB_USERNAME: requestrepouser
      MONGODB_PASSWORD: changethis
      MONGODB_HOSTNAME: mongodb
      DOMAIN: requestrepo.com
      SERVER_IP: 159.89.104.197
  flaskapp:
    build: .
    container_name: flaskapp
    restart: always
    ports:
      - 21337:21337
    environment:
      MONGODB_DATABASE: requestrepo
      MONGODB_USERNAME: requestrepouser
      MONGODB_PASSWORD: changethis
      MONGODB_HOSTNAME: mongodb
      DOMAIN: requestrepo.com
      JWT_SECRET: changethis
    depends_on:
      - mongodb
  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/fullchain.pem:/etc/nginx/fullchain.pem
      - ./nginx/privkey.pem:/etc/nginx/privkey.pem
volumes:
  mongodb_data:
    driver: local
