version: '3.1'

services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: requestrepouser
      MONGO_INITDB_ROOT_PASSWORD: changethis
    ports:
      - 27017:27017